=== PaymentsNZ/API-Security-Profile/working/V2.0-draft3/hybrid-flow/authorization-request-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://apicentre.paymentsnz.co.nz/schemas/authorization-request-schema.json",
  "type": "object",
  "title": "The schema for the Authorisation Request (OIDC/FAPI compliant) token",
  "additionalProperties": false,
  "required": [
    "aud",
    "iss",
    "response_type",
    "client_id",
    "redirect_uri",
    "scope",
    "state",
    "nonce",
    "claims"
  ],
  "properties": {
    "aud": {
      "$id": "#/properties/aud",
      "title": "The audiences for the token",
      "description": "The value should be or include the API Provider Issuer Identifier URL",
      "oneOf": [
        {
          "type": "string",
          "examples": ["https://api.alphanbank.com"],
          "format": "uri"
        },
        {
          "type": "array",
          "$id": "#/properties/aud/items",
          "items": {
            "type": "string",
            "pattern": "^(.+)$"
          },
          "examples": ["https://api.alphanbank.com"]
        }
      ]
    },
    "iss": {
      "$id": "#/properties/iss",
      "type": "string",
      "title": "The Issuer of the token",
      "description": "The value should be the client ID of the third party, unless signed by a different party",
      "default": "",
      "examples": ["s6BhdRkqt3"],
      "pattern": "^(.+)$"
    },
    "response_type": {
      "$id": "#/properties/response_type",
      "type": "string",
      "title": "The type of the response token",
      "default": "code id_token",
      "examples": ["code id_token"],
      "pattern": "^code id_token$"
    },
    "client_id": {
      "$id": "#/properties/client_id",
      "type": "string",
      "title": "The ID of the third-party client",
      "default": "",
      "examples": ["s6BhdRkqt3"],
      "pattern": "^(.+)$"
    },
    "redirect_uri": {
      "$id": "#/properties/redirect_uri",
      "type": "string",
      "title": "The URI to which to redirect the customer User Agent",
      "default": "",
      "examples": ["https://api.mytpp.com/cb"],
      "format": "uri"
    },
    "scope": {
      "$id": "#/properties/scope",
      "type": "string",
      "title": "The OAuth scopes requested",
      "description": "Must include 'openid' and any other scopes required",
      "default": "openid",
      "examples": ["openid payments"],
      "pattern": "^openid([ ].*)*$"
    },
    "state": {
      "$id": "#/properties/state",
      "type": "string",
      "title": "The third-party specific state",
      "description": "Opaque to API provider",
      "default": "",
      "examples": ["af0ifjsldkj"],
      "pattern": "^(.+)$"
    },
    "nonce": {
      "$id": "#/properties/nonce",
      "type": "string",
      "title": "Third party nonce to avoid replay",
      "default": "",
      "examples": ["n-0S6_WzA2Mj"],
      "pattern": "^(.+)$"
    },
    "max_age": {
      "$id": "#/properties/max_age",
      "type": "integer",
      "title": "Third-party specified maximum authentication age",
      "default": 0,
      "examples": [86400]
    },
    "claims": {
      "$id": "#/properties/claims",
      "type": "object",
      "title": "Claims object that holds the id_token request",
      "required": ["id_token"],
      "properties": {
        "id_token": {
          "$id": "#/properties/claims/properties/id_token",
          "type": "object",
          "title": "The ID token request claims",
          "required": ["ConsentId"],
          "properties": {
            "ConsentId": {
              "$id": "#/properties/claims/properties/id_token/properties/ConsentId",
              "type": "object",
              "title": "The Consent ID object",
              "required": ["value", "essential"],
              "properties": {
                "value": {
                  "$id": "#/properties/claims/properties/id_token/properties/ConsentId/properties/value",
                  "type": "string",
                  "title": "The value of Consent ID",
                  "default": "",
                  "examples": ["urn-alphabank-intent-58923"],
                  "pattern": "^(.+)$"
                },
                "essential": {
                  "$id": "#/properties/claims/properties/id_token/properties/ConsentId/properties/essential",
                  "type": "boolean",
                  "title": "Essential claim identifier",
                  "default": false,
                  "examples": [true]
                }
              }
            }
          }
        }
      }
    }
  }
}

=== PaymentsNZ/API-Security-Profile/working/V2.0.0-rc2/examples/authentication-request.json
{
    "aud": [
      "https://api.examplebank.co.nz",
      "https://auth.examplebank.co.nz",
      "https://id.thirdparty.co.nz"
    ],
    "iss": "thirdparty-client-id",
    "response_type": "code id_token",
    "client_id": "thirdparty-client-id",
    "redirect_uri": "https://app.thirdparty.co.nz",
    "scope": "openid payments",
    "state": "YNynJYrcq?idasewrasdf",
    "nonce": "dasc-rhshtma/jhsouen",
    "max_age" : 7200,
    "claims": {
      "id_token": {
        "ConsentId": {
          "value": "urn-examplebank-co-nz-12376793",
          "essential": true
        }
      }
    }
  }

=== PaymentsNZ/API-Security-Profile/working/V2.0.0-rc2/examples/authentication-request-2.json
{
    "aud": "https://api.examplebank.co.nz",
    "iss": "thirdparty-client-id",
    "response_type": "code id_token",
    "client_id": "thirdparty-client-id",
    "redirect_uri": "https://app.thirdparty.co.nz",
    "scope": "openid payments",
    "state": "YNynJYrcq?idasewrasdf",
    "nonce": "dasc-rhshtma/jhsouen",
    "claims": {
      "id_token": {
        "ConsentId": {
          "value": "urn-examplebank-co-nz-12376793",
          "essential": true
        }
      }
    }
  }
