=== PaymentsNZ/API-Security-Profile/working/V2.0-draft3/ciba-flow/token-request-response-schema.json
{
    "definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://apicentre.paymentsnz.co.nz/schemas/token-request-response-schema.json",
	"type": "object",
    "title": "The schema for the Open ID Connect token request response",
    "additionalProperties": false,
    "required": [
        "access_token",
        "token_type",
        "expires_in",
        "id_token"
    ],
    "properties": {
        "access_token" : {
            "$id": "/properties/access_token",
            "type": "string",
            "title": "Access token",
            "description": "The token to be used on subsequent API requests",
            "examples": [
                "G5kXH2wHvUra0sHlDy1iTkDJgsgUO1bN"
            ]
        },
        "token_type": {
            "$id": "/properties/token_type",
            "type": "string",
            "title": "The OAuth 2.0 token type",
            "enum": [
                "Bearer", "mac"
            ]
        },
        "refresh_token": {
            "$id": "/properties/refresh_token",
            "type": "string",
            "title": "Refresh token",
            "description": "The token to be used to refresh the access token",
            "examples": [
                "4bwc0ESC_IAhflf-ACC_vjD_ltc11ne-8gFPfA2Kx16"
            ]
        },
        "expires_in": {
            "$id": "/properties/expires_in",
            "type": "integer",
            "exclusiveMinimum": 0,
            "title": "Access token expiry time",
			"description": "A positive integer value in seconds, indicating the expiration time since the authentication request was received",
			"examples": [
				3600
			]
        },
        "id_token": {
            "$id": "/properties/id_token",
            "type": "string",
            "title": "The ID Token issued to the third party",
            "pattern": "^[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_.+/=]*$"
        }
    }
}

=== PaymentsNZ/API-Security-Profile/working/V2.0.0-rc2/examples/token-request-response.json
{
    "access_token": "G5kXH2wHvUra0sHlDy1iTkDJgsgUO1bN",
    "token_type": "Bearer",
    "refresh_token": "4bwc0ESC_IAhflf-ACC_vjD_ltc11ne-8gFPfA2Kx16",
    "expires_in": 3600,
    "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE2NzcyNiJ9.eyJpc3MiOiJodHRwczovL3NlcnZlci5leGFtcGxlLmNvbSIsInN1YiI6IjI0ODI4OTc2MTAwMSIsImF1ZCI6InM2QmhkUmtxdDMiLCJlbWFpbCI6ImphbmVkb2VAZXhhbXBsZS5jb20iLCJleHAiOjE1Mzc4MTk4MDMsImlhdCI6MTUzNzgxOTUwM30.aVq83mdy72ddIFVJLjlNBX-5JHbjmwK-Sn9Mir-blesfYMceIOw6u4GOrO_ZroDnnbJXNKWAg_dxVynvMHnk3uJc46feaRIL4zfHf6Anbf5_TbgMaVO8iczD16A5gNjSD7yenT5fslrrW-NU_vtmi0s1puoM4EmSaPXCR19vRJyWuStJiRHK5yc3BtBlQ2xwxH1iNP49rGAQe_LHfW1G74NY5DaPv-V23JXDNEIUTY-jT-NbbtNHAxnhNPyn8kcO2WOoeIwANO9BfLF1EFWtjGPPMj6kDVrikec47yK86HArGvsIIwk1uExynJIv_tgZGE0eZI7MtVb2UlCwDQrVlg"
}
